repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.11
  hooks:
    # Run the linter.
    # - id: ruff-check
    #   args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      files: ^server/.+\.py$
- repo: https://github.com/biomejs/pre-commit
  rev: v1.9.4 # Use the sha / tag you want to point at
  hooks:
    # - id: biome-check
    #   files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
    - id: biome-format
      files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
      exclude: ^(__generated__|.*/__generated__)/
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.0
  hooks:
    - id: terraform_fmt
      files: ^infrastructure/.+\.tf$
    - id: terraform_tflint
      files: ^infrastructure/.+\.tf$
