name: medical_jobs
root: ./

windows:
  - server:
        - cd server
        - uv run scripts/run_server.py

  - seeker_portal:
      layout: even-horizontal
      panes:
        - next-server:
          - cd apps/seeker-portal
          - pnpm run dev
        - relay:
          - cd apps/seeker-portal
          - pnpm run relay --watch

  - recruiter_portal:
      layout: even-horizontal
      panes:
        - next-server:
          - cd apps/recruiter-portal
          - pnpm run dev
        - relay:
          - cd apps/recruiter-portal
          - pnpm run relay --watch

  - accounts:
      layout: even-horizontal
      panes:
        - next-server:
          - cd apps/accounts
          - pnpm run dev
        - relay:
          - cd apps/accounts
          - pnpm run relay --watch

  - docker:
      - docker compose up
