name: medical_jobs
root: ./

windows:
  - server:
      layout: even-horizontal
      panes:
        -  dev:
            - cd server
            - uv run scripts/run_server.py
        -  persist:
            - cd server
            - uv run scripts/run_persist_server.py
  -  langgraph_agent:
        - cd server
        - uv run langgraph dev --allow-blocking --port 8123

  - seeker_portal:
      - pnpm --filter seeker-portal dev

  - recruiter_portal_core:
      - pnpm --filter recruiter-portal-core dev

  - recruiter_dashboard:
      - pnpm --filter recruiter-dashboard dev

  - accounts:
      - pnpm --filter accounts dev

  - relay-compiler:
      - relay-compiler --watch

  - docker:
      - docker compose up
