name: medical_jobs
root: ./

windows:
  - server:
      layout: even-horizontal
      panes:
        - cd server && uv run scripts/run_server.py
  - seeker_portal:
      layout: even-horizontal
      panes:
        - cd apps/seeker-portal && pnpm run dev
  - docker:
      panes:
        - docker compose up
