name: medical_jobs
root: ./

windows:
  - server:
        - cd server
        - uv run scripts/run_server.py

  - seeker_portal:
        - cd apps/seeker-portal
        - pnpm run dev

  - recruiter_portal:
        - cd apps/recruiter-portal
        - pnpm run dev

  - accounts:
        - cd apps/accounts
        - pnpm run dev

  - docker:
      panes:
        - docker compose up
