name: medical_jobs
root: ./

windows:
  - server:
      layout: even-horizontal
      panes:
        -  dev:
            - cd server
            - uv run scripts/run_server.py
        -  persist:
            - cd server
            - uv run scripts/run_persist_server.py
  -  langgraph_agent:
        - cd server
        - uv run langgraph dev --allow-blocking --port 8123

  - seeker_portal:
        - cd apps/seeker-portal
        - pnpm run dev

  - recruiter_portal_core:
        - cd apps/recruiter-portal-core
        - pnpm run dev

  - recruiter_portal:
        - cd apps/recruiter-dashboard
        - pnpm run dev

  - accounts:
        - cd apps/accounts
        - pnpm run dev

  - relay-compiler:
      - relay-compiler --watch

  - docker:
      - docker compose up
