services:
  mongodb:
    image: docker.io/bitnami/mongodb:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE=medical_jobs
      - MONGODB_ROOT_PASSWORD=rootpass
    volumes:
      - "mongodb_data:/bitnami/mongodb"

volumes:
  mongodb_data:
