services:
  mongodb:
    image: docker.io/bitnami/mongodb:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE=medical_jobs
      - MONGODB_ROOT_PASSWORD=rootpass
    volumes:
      - "mongodb_data:/bitnami/mongodb"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  # caddy:
  #   build:
  #     context: ./caddy
  #     dockerfile: Dockerfile
  #     target: development
  #   restart: always
  #   volumes:
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:80"]
  #     interval: 5s
  #     timeout: 1s
  #     retries: 3
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

volumes:
  mongodb_data:
    driver: local
  # caddy_data:
  #   driver: local
  # caddy_config:
  #   driver: local
