name: "Detect Paths Changed"

description: "Composite action to detect changes to specified files between commits"

inputs:
  paths:
    description: "Newline-separated list of file globs to check for changes"
    required: true
    default: |
      server/query_map.json

outputs:
  changed:
    description: "'true' if any of the specified paths changed, otherwise 'false'"

runs:
  using: "composite"
  steps:
    - name: Checkout full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect changes
      id: diff
      shell: bash
      run: |
        # Default to no changes on non-push events
        if [[ "${{ github.event_name }}" != "push" ]]; then
          echo "::set-output name=changed::false"
          exit 0
        fi

        BEFORE=${{ github.event.before }}
        AFTER=${{ github.event.after }}

        # Handle missing or invalid BEFORE commit
        if [[ -z "$BEFORE" ]] || ! git cat-file -e "${BEFORE}^{commit}" 2>/dev/null; then
          echo "No valid before commit; assuming no changes"
          echo "::set-output name=changed::false"
          exit 0
        fi

        echo "Diffing $BEFORE → $AFTER for paths:" 
        echo "${{ inputs.paths }}"

        # Loop through each path on the same line
        IFS=$'\n'
        for path in ${{ inputs.paths }}; do
          if git diff --name-only "$BEFORE" "$AFTER" -- "$path" | grep -q .; then
            echo "Detected changes in $path"
            echo "::set-output name=changed::true"
            exit 0
          fi
        done

        echo "No changes detected in specified paths"
        echo "::set-output name=changed::false"
