name: "Detect Path Changed"

description: "Composite action to detect changes to a specified file between commits"

inputs:
  path:
    description: "File path to check for changes between commits"
    required: true
    default: "server/query_map.json"

outputs:
  changed:
    description: "'true' if the specified file changed, otherwise 'false'"

runs:
  using: "composite"
  steps:
    - name: Checkout full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Detect changes
      id: diff
      shell: bash
      run: |
        # Default to no changes on non-push events
        if [[ "${{ github.event_name }}" != "push" ]]; then
          echo "::set-output name=changed::false"
          exit 0
        fi

        BEFORE=${{ github.event.before }}
        AFTER=${{ github.event.after }}
        TARGET_PATH="${{ inputs.path }}"

        # Handle missing or invalid BEFORE commit
        if [[ -z "$BEFORE" ]] || ! git cat-file -e "${BEFORE}^{commit}" 2>/dev/null; then
          echo "No valid before commit; assuming no changes"
          echo "changed=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "Diffing $BEFORE → $AFTER for file: $TARGET_PATH"
        if git diff --name-only "$BEFORE" "$AFTER" -- "$TARGET_PATH" | grep -q .; then
          echo "Detected changes in $TARGET_PATH"
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "No changes detected in $TARGET_PATH"
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
