[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioinject>=0.35.3",
    "asgi-correlation-id>=4.3.4",
    "fastapi>=0.115.5",
    "pydantic>=2.10.2",
    "pydantic-settings>=2.6.1",
    "strawberry-graphql[cli]>=0.253.0",
    "structlog>=24.4.0",
    "beanie>=1.27.0",
    "motor>=3.6.0",
    "uvicorn[standard]>=0.32.1",
    "passlib[argon2]>=1.7.4",
    "result>=0.17.0",
    "authlib>=1.4.0",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "aiosmtplib>=3.0.2",
    "jinja2>=3.1.5",
    "humanize>=4.11.0",
    "email-validator>=2.2.0",
    "boto3>=1.36.1",
    "aioboto3>=13.4.0",
    "pymongo>=4.9.2",
]

[tool.uv]
dev-dependencies = [
    "types-passlib>=1.7.7.20241221",
    "types-aioboto3[essential]>=13.4.0",
    "types-authlib>=1.4.0.20241230",
]
