[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioinject>=0.35.3",
    "asgi-correlation-id>=4.3.4",
    "fastapi>=0.115.5",
    "pydantic>=2.10.2",
    "pydantic-settings>=2.6.1",
    "strawberry-graphql[cli]>=0.253.0",
    "structlog>=24.4.0",
    "beanie>=1.27.0",
    "motor>=3.6.0",
    "uvicorn[standard]>=0.32.1",
    "requests>=2.32.3",
    "pyjwt>=2.10.1",
    "cryptography>=44.0.0",
    "types-aioboto3[cognito-idp]>=13.2.0.post2",
    "boto3>=1.35.36",
    "aioboto3>=13.2.0",
]
