name: Build and Deploy Accounts UI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/accounts/**'
      - '.github/workflows/deploy-accounts-ui.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEPLOYMENT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOYMENT_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        working-directory: ./apps/accounts
        run: pnpm install --frozen-lockfile --shamefully-hoist

      - name: Create artifacts directory
        working-directory: ./apps/accounts
        run: mkdir -p ./__generated__

      - name: SST Deploy
        working-directory: ./apps/accounts
        run: npx sst deploy --stage production
        env:
            SST_VPC_PRIVATE_SUBNETS: ${{ vars.SST_VPC_PRIVATE_SUBNETS }}
            SST_VPC_SECURITY_GROUPS: ${{ vars.SST_VPC_SECURITY_GROUPS }}
            SST_ACCOUNTS_DOMAIN: ${{vars.SST_ACCOUNTS_DOMAIN }}
            NEXT_PUBLIC_API_URL: ${{ vars.SST_API_URL }}
            NEXT_PUBLIC_URL: ${{ vars.SST_ACCOUNTS_BASE_URL }}
            NEXT_PUBLIC_CAPTCHA_SITE_KEY: ${{ vars.SST_CAPTCHA_SITE_KEY }}
            NEXT_PUBLIC_RECRUITER_PORTAL_BASE_URL: ${{ vars.SST_RECRUITER_PORTAL_BASE_URL }}
            NEXT_PUBLIC_SEEKER_PORTAL_BASE_URL: ${{ vars.SST_SEEKER_PORTAL_BASE_URL}}
            API_URL: ${{ vars.SST_API_URL }}
            JWE_SECRET_KEY: ${{ secrets.SST_JWE_SECRET_KEY }}

            
# TODO: wait for relevant tests to pass before building and pushing