name: Deploy SST Router

on:
  push:
    branches:
      - main
    paths:
      - 'sst-router/**'

concurrency:
  group: ${{ github.workflow }}  # Ensures only one run of this workflow at a time
  cancel-in-progress: false      # Waits instead of cancelling previous runs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEPLOYMENT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOYMENT_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: SST Deploy
        working-directory: ./sst-deploy
        run: npx sst deploy --stage production --print-logs
        env:
            NODE_ENV: production
