name: E2E Tests
on: [push]
jobs:
  test-accounts:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: docker.io/bitnami/mongodb:8.0
        ports:
          - "27017:27017"
        env:
          MONGODB_USERNAME: user
          MONGODB_PASSWORD: pass
          MONGODB_DATABASE: medical_jobs_test
          MONGODB_ROOT_PASSWORD: rootpass
      
    defaults:
        run:
          working-directory: apps/accounts
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
            version: 10
      - name: Install dependencies and playwright binaries
        run: pnpm install && npx playwright install --with-deps
      - name: Setup environment variables
        run: |
          echo "NEXT_PUBLIC_API_URL=http://localhost:8000" >> .env
          echo "NEXT_PUBLIC_URL=http://localhost:5002" >> .env
          echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=" >> .env
          echo "NEXT_PUBLIC_RECRUITER_PORTAL_BASE_URL=http://localhost:5001" >> .env
          echo "NEXT_PUBLIC_SEEKER_PORTAL_BASE_URL=http://localhost:5000" >> .env
          echo "JWE_SECRET_KEY="ca07d5f965a534ffb07d1699e30385a6"" >> .env
          echo "CI=true" >> .env
    #   - name: Push schema to database
    #     run: npx prisma db push && npx prisma generate
      - name: Create __generated__ directory
        run: mkdir -p __generated__
      - name: Build Application
        run: pnpm build
      - name: Run Playwright tests
        run: pnpm test:e2e