name: E2E Tests
on: [push]

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

jobs:
  test-accounts:
    name: 'Test on ${{ matrix.project }} (${{ matrix.shard }}/4)'
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]
        shard: [1, 2, 3, 4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: docker compose -f docker-compose.e2e.yml up --build -d --wait --remove-orphans

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: apps/accounts/pnpm-lock.yaml 
  
      - name: Install dependencies 
        run: pnpm install
        working-directory: apps/accounts

      - name: Install Playwright
        id: install-playwright
        uses: ./.github/actions/playwright
        with:
          working-directory: apps/accounts

      - name: Debug Playwright cache
        run: |
          echo "Playwright version – ${{ steps.install-playwright.outputs.version }}"
          echo "Playwright cached – ${{ steps.install-playwright.outputs.cache-hit }}"

      - name: Create Playwright Browser State Directory
        run : mkdir -p playwright/.auth
        working-directory: apps/accounts
  
      - name: Run Playwright tests
        run: pnpm test:e2e --trace=on --project=${{ matrix.project }} --shard=${{ matrix.shard }}/4
        working-directory: apps/accounts
        env:
          CI: true
          DEBUG: pw:browser
  
      - name: Upload Playwright Report and Traces
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}-${{ matrix.shard }}
          path: |
            apps/accounts/playwright-report/
            apps/accounts/test-results/**/*.zip
          retention-days: 30

    