name: E2E Tests
on: [push]

jobs:
  test-accounts:
    runs-on: ubuntu-latest
      
    defaults:
        run:
          working-directory: apps/accounts
    steps:
      - uses: actions/checkout@v3

      - run: docker compose build
      - run: docker compose down -v --remove-orphans
      - name: Run Playwright tests
        run: docker compose run --rm playwright npx playwright test --fail-on-flaky-tests --trace=retain-on-failure
      - run: docker compose down -v --remove-orphans