name: E2E Tests
on: [push]

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

jobs:
  test-accounts:
    name: 'Test on ${{ matrix.project }} (${{ matrix.shard }}/4)'
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, webkit]
        shard: [1, 2, 3, 4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker compose -f docker-compose.e2e.yml up --build -d --wait --remove-orphans
      - name: Check if server is running
        run: curl -v http://localhost:5002 || (echo "Server not running!" && exit 1)

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: apps/accounts/pnpm-lock.yaml 
           
      - name: Install dependencies and Playwright browsers  
        run: pnpm install && npx playwright install-deps
        working-directory: apps/accounts
      - name: Run Playwright tests
        run: pnpm test:e2e --trace=on --project=${{ matrix.project }} --shard=${{ matrix.shard }}/4
        working-directory: apps/accounts
        env:
          CI: true
          DEBUG: pw:browser
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.project }}-${{ matrix.shard }}
          path: playwright-report/
          retention-days: 30
    